---
title: "Conferences"
---

<br>

## 2023

> School District TEL Stringency and Education-Supporting Nonprofit Revenues: 2023 Crowding Out Community Support to Supplement School Revenues. Korean Association of Public Administration.

> School District TEL Stringency and the Finances of Education-Supporting Nonprofits: Crowding Out Community Support to Supplement School Revenues. Association of Education Finance and Policy

### 2022

> Do Nonprofits Substitute Educational Resources in Response to Tax and Expenditure Limits on School Districts?
Association for Budgeting and Financial Management.

> Property tax levies relative to predetermined options:  Exploiting fiscal illusion? Association for Public Policy Analysis & Management.

### 2021

> The effects of removing voter recall from school district property taxes. Association for Budgeting and Financial Management.

### 2019

> The impact of state oversight on property assessments and school district revenues. Association for Public Policy Analysis & Management. [Presentation](static-files/pa_oversight_appam2019.pdf)

> Does state intervention in local property assessments impact school finance equalization? Association of Education Finance and Policy.

<br>

### 2018

> High-tuition, high-aid policy and college expenditures. Association of Education Finance and Policy. [Presentation](static-files/htha_aefp2018.pdf)

> Are state subsidies in higher education driving a divergence in institutional expenditures? Association for Budgeting and Financial Management.

<br>

### 2017

> The effect of NCLB waivers on college outcomes. Association for Public Policy Analysis & Management. [Presentation](static-files/waivers_appam2017.pdf)

> The effect of No Child Left Behind Sanctions on College Outcomes:  Examining Kentucky's ESEA Waiver. Association of Education Finance and Policy. [Poster](static-files/waivers_abfm2017.pdf)

> Local response to school finance equalization: The important of place. Association for Public Policy Analysis & Management. [Presentation](static-files/sfe_appam2017.pdf)

> Local response to school finance equalization. Association for Budgeting and Financial Management.

<br>

### 2016

> The effect of distance on degree completion. Association of Education Finance and Policy. [Presentation](static-files/distance_aefp2016.pdf)

<br>

### 2015

> Trends and determinants of state government privatization activity. Association for Budgeting and Financial Management. [Presentation](static-files/privatization_abfm2015.pdf)