---
title: "Writing"
---
***
<br>

## Refereed Publications

> Combs, A.E., & Foster, J. (2021). The effects of homestead exemptions for seniors and disabled people on school districts. Rural Education Finance and Policy, special issue of AERA Open.
https://doi.org/10.1177%2F2332858420988712

> Combs, A.E., Foster, J., & Toma E.F. (2018). Local response to school finance equalization:  Wealth or place? Public Finance and Management, 18(3). [https://pfm.spaef.org/article/1856/Local-Responses-to-School-Finance-Equalization-Wealth-or-Place-](https://pfm.spaef.org/article/1856/Local-Responses-to-School-Finance-Equalization-Wealth-or-Place-)

<br>

## Under Review & In Preparation

> Combs, A.E. State Sales Tax Revenue Generated by Daily K-12 School Operations: In- sights From COVID School Closures

> Combs, A.E. The Impact of School Board Governance and Membership on the Distribu- tion of District Funds to Schools

> Buerger, C., Combs, A.E., Afonso, W. Plugging the Tax Leak: An Analysis of North Carolina’s Local Sales Tax Redistribution Policy

> Combs, A.E, & Kim, Saerim. School District TEL Severity and the Finances of Education- Supporting Nonprofits: Crowding-out Community Support to Supplement School Rev- enues

> Combs, A.E. Fiscal Illusion Under the Cover of Property Tax Limits: School District Revenue Response to a Reordering of Tax Levy Options

> Combs, A.E. The Expenditure Response of Higher Education Institutions to Changes in State Subsidies and Simulated Impacts on Graduation Rates

> Combs, A.E. The Impact of Distance for Students Seeking an Associate or Bachelor’s Degree at In-State Public Institutions

> Combs, A.E. High School Student Achievement and College Enrollment in the Absence of School Improvement Interventions: Evidence from Kentucky

> Combs, A.E., Foster, J., & Troland E. Can State Oversight Improve Local Property As- sessments? Evidence from Education Finance Reform in Kentucky

<br>

## Other

> Combs, A.E., Foster, J., & Troland, E. The Role of Property Assessment Oversight in School Finance Inequality. Finance and Economics Discussion Series. Board of Governors of the Federal Reserve System. https://doi.org/10.17016/FEDS.2023.024

> Combs, Alex Eugene, "STATE SUBSIDY COMPOSITION IN HIGHER EDUCATION: POLICY AND IMPACTS" (2018). Theses and Dissertations--Public Policy and Administration. 29. [https://uknowledge.uky.edu/msppa_etds/29](https://uknowledge.uky.edu/msppa_etds/29)

> Combs, Alex E., "Does Kentucky’s Merit-based Scholarship Program, KEES, Improve College Completion?" (2014). MPA/MPP Capstone Projects. 219. 
[https://uknowledge.uky.edu/mpampp_etds/219](https://uknowledge.uky.edu/mpampp_etds/219)